import type { Cliente, PipelineEstado } from "../types";

// Anunciantes ficticios con tono argentino. Fecha de referencia del demo: 2026-06-20.

type Seed = {
  id: string;
  razonSocial: string;
  rubro: string;
  contactoNombre: string;
  contactoCargo: string;
  email: string;
  telefono: string;
  estado: PipelineEstado;
  valorEstimado: number;
  fuente: string;
  prioridad: "alta" | "media" | "baja";
  color: string;
  creadoEl: string;
  acts: [string, Cliente["actividades"][number]["tipo"], string][]; // [fechaISO, tipo, texto]
};

const S: Seed[] = [
  {
    id: "cli-polo-norte",
    razonSocial: "Heladerías Polo Norte",
    rubro: "Gastronomía",
    contactoNombre: "Mariana Lasalle",
    contactoCargo: "Gerenta de Marketing",
    email: "mariana@polonorte.com.ar",
    telefono: "+54 11 5512-3344",
    estado: "activo",
    valorEstimado: 1440000,
    fuente: "Referido",
    prioridad: "alta",
    color: "#2563eb",
    creadoEl: "2026-02-10T13:00:00",
    acts: [
      ["2026-02-10T13:00:00", "reunion", "Reunión inicial. Quieren campaña de temporada de verano en zona norte."],
      ["2026-02-18T15:30:00", "propuesta", "Enviamos propuesta de 2 carteles en Belgrano y Núñez."],
      ["2026-03-01T11:00:00", "whatsapp", "Confirmaron. Firmamos contrato por 6 meses."],
      ["2026-06-05T10:00:00", "llamada", "Llamada de seguimiento: muy conformes con la visibilidad."],
    ],
  },
  {
    id: "cli-banco-plata",
    razonSocial: "Banco del Plata",
    rubro: "Finanzas",
    contactoNombre: "Esteban Quirós",
    contactoCargo: "Brand Manager",
    email: "equiros@bancodelplata.com.ar",
    telefono: "+54 11 4788-0099",
    estado: "activo",
    valorEstimado: 4980000,
    fuente: "Inbound web",
    prioridad: "alta",
    color: "#0f766e",
    creadoEl: "2026-01-15T09:00:00",
    acts: [
      ["2026-01-15T09:00:00", "email", "Pidieron disponibilidad de medianeras y LED en corredores premium."],
      ["2026-01-22T16:00:00", "reunion", "Presentación. Buscan presencia institucional todo el año."],
      ["2026-02-01T12:00:00", "propuesta", "Propuesta anual de 3 ubicaciones premium."],
      ["2026-02-12T10:30:00", "nota", "Contrato anual firmado. Renovación automática a evaluar."],
    ],
  },
  {
    id: "cli-cerveceria",
    razonSocial: "Cervecería Riachuelo",
    rubro: "Bebidas",
    contactoNombre: "Lucas Beltrán",
    contactoCargo: "Director Comercial",
    email: "lucas@riachuelobeer.com",
    telefono: "+54 11 6634-7711",
    estado: "activo",
    valorEstimado: 2100000,
    fuente: "Evento del rubro",
    prioridad: "media",
    color: "#b45309",
    creadoEl: "2026-03-20T14:00:00",
    acts: [
      ["2026-03-20T14:00:00", "reunion", "Lanzamiento de variedad IPA. Quieren impacto en Palermo."],
      ["2026-03-28T11:00:00", "propuesta", "Propuesta LED Palermo + frontal Villa Crespo."],
      ["2026-04-05T17:00:00", "whatsapp", "Aceptaron. Campaña activa desde abril."],
    ],
  },
  {
    id: "cli-automotores",
    razonSocial: "Automotores Pampa",
    rubro: "Automotriz",
    contactoNombre: "Diego Sosa",
    contactoCargo: "Jefe de Marketing",
    email: "dsosa@autopampa.com.ar",
    telefono: "+54 11 5090-2211",
    estado: "negociando",
    valorEstimado: 3300000,
    fuente: "Referido",
    prioridad: "alta",
    color: "#b91c1c",
    creadoEl: "2026-05-22T10:00:00",
    acts: [
      ["2026-05-22T10:00:00", "llamada", "Lanzan modelo 0km. Interesados en alto tránsito vehicular."],
      ["2026-05-29T15:00:00", "propuesta", "Propuesta: medianera Gral. Paz + LED Cabildo."],
      ["2026-06-11T12:30:00", "reunion", "Negociando descuento por 4 meses. Pidieron ajustar precio."],
      ["2026-06-18T09:30:00", "email", "Enviamos contrapropuesta con 8% off. Esperando respuesta."],
    ],
  },
  {
    id: "cli-universidad",
    razonSocial: "Universidad del Río",
    rubro: "Educación",
    contactoNombre: "Paula Genovese",
    contactoCargo: "Coord. de Comunicación",
    email: "pgenovese@udelrio.edu.ar",
    telefono: "+54 11 4322-5566",
    estado: "negociando",
    valorEstimado: 1320000,
    fuente: "Inbound web",
    prioridad: "media",
    color: "#7c3aed",
    creadoEl: "2026-05-30T11:00:00",
    acts: [
      ["2026-05-30T11:00:00", "email", "Campaña de inscripciones del segundo cuatrimestre."],
      ["2026-06-06T14:00:00", "propuesta", "Propuesta de 2 frontales en Caballito y Almagro."],
      ["2026-06-16T10:00:00", "whatsapp", "Pidieron sumar una tercera ubicación. Recotizando."],
    ],
  },
  {
    id: "cli-telco",
    razonSocial: "Telco Conecta",
    rubro: "Telecomunicaciones",
    contactoNombre: "Hernán Vidal",
    contactoCargo: "Media Manager",
    email: "hvidal@conecta.com.ar",
    telefono: "+54 11 6700-8899",
    estado: "propuesta",
    valorEstimado: 5400000,
    fuente: "Agencia de medios",
    prioridad: "alta",
    color: "#0891b2",
    creadoEl: "2026-06-08T09:00:00",
    acts: [
      ["2026-06-08T09:00:00", "reunion", "Briefing de campaña 5G. Quieren cobertura en toda CABA."],
      ["2026-06-13T16:00:00", "propuesta", "Propuesta enviada: pack de 5 carteles premium."],
    ],
  },
  {
    id: "cli-super-estrella",
    razonSocial: "Supermercados La Estrella",
    rubro: "Retail",
    contactoNombre: "Carla Funes",
    contactoCargo: "Marketing Regional",
    email: "cfunes@laestrella.com.ar",
    telefono: "+54 11 4555-1212",
    estado: "propuesta",
    valorEstimado: 1860000,
    fuente: "Referido",
    prioridad: "media",
    color: "#dc2626",
    creadoEl: "2026-06-10T13:00:00",
    acts: [
      ["2026-06-10T13:00:00", "llamada", "Promoción de aniversario. Foco barrios residenciales."],
      ["2026-06-15T11:30:00", "propuesta", "Propuesta de 3 frontales en Flores, Caballito y Villa Urquiza."],
    ],
  },
  {
    id: "cli-indumentaria",
    razonSocial: "Indumentaria Andes",
    rubro: "Indumentaria",
    contactoNombre: "Sofía Marenco",
    contactoCargo: "Dueña",
    email: "sofia@andeswear.com",
    telefono: "+54 11 3344-7788",
    estado: "propuesta",
    valorEstimado: 980000,
    fuente: "Instagram",
    prioridad: "baja",
    color: "#db2777",
    creadoEl: "2026-06-12T15:00:00",
    acts: [
      ["2026-06-12T15:00:00", "whatsapp", "Nueva colección invierno. Le interesa Palermo."],
      ["2026-06-17T12:00:00", "propuesta", "Propuesta de medianera Palermo enviada."],
    ],
  },
  {
    id: "cli-farmacias",
    razonSocial: "Farmacias Vida",
    rubro: "Salud",
    contactoNombre: "Roberto Páez",
    contactoCargo: "Gerente Comercial",
    email: "rpaez@farmaciasvida.com.ar",
    telefono: "+54 11 4900-3030",
    estado: "prospecto",
    valorEstimado: 1200000,
    fuente: "Llamado en frío",
    prioridad: "media",
    color: "#16a34a",
    creadoEl: "2026-06-14T10:00:00",
    acts: [
      ["2026-06-14T10:00:00", "llamada", "Primer contacto. Evaluando presencia en zona sur."],
    ],
  },
  {
    id: "cli-gimnasios",
    razonSocial: "Gimnasios Fuerza",
    rubro: "Fitness",
    contactoNombre: "Nadia Rial",
    contactoCargo: "Marketing",
    email: "nadia@fuerzagym.com",
    telefono: "+54 11 6121-4545",
    estado: "prospecto",
    valorEstimado: 720000,
    fuente: "Inbound web",
    prioridad: "baja",
    color: "#ea580c",
    creadoEl: "2026-06-16T16:00:00",
    acts: [
      ["2026-06-16T16:00:00", "email", "Consultaron por carteles cerca de sus sedes."],
    ],
  },
  {
    id: "cli-delivery",
    razonSocial: "Delivery Ya Llega",
    rubro: "Apps / Tech",
    contactoNombre: "Tomás Iriarte",
    contactoCargo: "Growth Lead",
    email: "tomas@yallega.app",
    telefono: "+54 11 7001-9090",
    estado: "prospecto",
    valorEstimado: 2600000,
    fuente: "Agencia de medios",
    prioridad: "alta",
    color: "#65a30d",
    creadoEl: "2026-06-18T11:00:00",
    acts: [
      ["2026-06-18T11:00:00", "reunion", "Quieren awareness fuerte y digital. Pidieron disponibilidad de LED."],
    ],
  },
  {
    id: "cli-seguros",
    razonSocial: "Seguros Confianza",
    rubro: "Seguros",
    contactoNombre: "Verónica Ledesma",
    contactoCargo: "Jefa de Marca",
    email: "vledesma@confianza.com.ar",
    telefono: "+54 11 4111-2323",
    estado: "vencido",
    valorEstimado: 1680000,
    fuente: "Referido",
    prioridad: "alta",
    color: "#1d4ed8",
    creadoEl: "2025-09-01T10:00:00",
    acts: [
      ["2025-09-01T10:00:00", "reunion", "Campaña institucional fin de 2025."],
      ["2025-09-15T12:00:00", "nota", "Contrato 3 meses en Recoleta y Belgrano (oct-dic 2025)."],
      ["2026-01-10T11:00:00", "whatsapp", "Campaña cerrada. Quedaron muy conformes."],
      ["2026-06-02T15:00:00", "llamada", "Reactivar: posible renovación para campaña de primavera."],
    ],
  },
  {
    id: "cli-cafe",
    razonSocial: "Café Tostado",
    rubro: "Gastronomía",
    contactoNombre: "Julián Bravo",
    contactoCargo: "Socio",
    email: "julian@cafetostado.com",
    telefono: "+54 11 5566-1010",
    estado: "vencido",
    valorEstimado: 540000,
    fuente: "Instagram",
    prioridad: "baja",
    color: "#92400e",
    creadoEl: "2025-11-05T14:00:00",
    acts: [
      ["2025-11-05T14:00:00", "whatsapp", "Apertura de local en Villa Crespo. Cartel cercano."],
      ["2025-11-20T10:00:00", "nota", "Contrato 2 meses (dic-ene). Cerrado."],
      ["2026-05-28T16:00:00", "email", "Consultar si abren nuevo local para reactivar."],
    ],
  },
];

export const clientesSeed: Cliente[] = S.map((s) => ({
  id: s.id,
  razonSocial: s.razonSocial,
  rubro: s.rubro,
  contactoNombre: s.contactoNombre,
  contactoCargo: s.contactoCargo,
  email: s.email,
  telefono: s.telefono,
  estado: s.estado,
  valorEstimado: s.valorEstimado,
  fuente: s.fuente,
  prioridad: s.prioridad,
  color: s.color,
  creadoEl: s.creadoEl,
  actividades: s.acts.map(([fecha, tipo, texto], i) => ({
    id: `${s.id}-act-${i}`,
    tipo,
    fecha,
    texto,
  })),
}));

// Taglines + paleta de arte por marca, para generar el "aviso" simulado.
export const marcaArte: Record<
  string,
  { tagline: string; bg: string; fg: string; accent?: string }
> = {
  "cli-polo-norte": { tagline: "El verano se vive frío", bg: "#2563eb", fg: "#ffffff" },
  "cli-banco-plata": { tagline: "Tu futuro, en buenas manos", bg: "#0f766e", fg: "#ffffff" },
  "cli-cerveceria": { tagline: "Nueva IPA de la casa", bg: "#b45309", fg: "#fff7ed", accent: "#fbbf24" },
  "cli-automotores": { tagline: "Estrená 0km hoy", bg: "#b91c1c", fg: "#ffffff" },
  "cli-universidad": { tagline: "Inscripciones abiertas", bg: "#6d28d9", fg: "#ffffff" },
  "cli-telco": { tagline: "Llegó el 5G a tu barrio", bg: "#0891b2", fg: "#ffffff", accent: "#67e8f9" },
  "cli-super-estrella": { tagline: "70 años con vos", bg: "#dc2626", fg: "#ffffff", accent: "#fde047" },
  "cli-indumentaria": { tagline: "Colección Invierno '26", bg: "#be185d", fg: "#ffffff" },
  "cli-seguros": { tagline: "Protegé lo que importa", bg: "#1d4ed8", fg: "#ffffff" },
  "cli-cafe": { tagline: "Recién tostado, cerca tuyo", bg: "#92400e", fg: "#fff7ed" },
};
